import type { MetadataRoute } from 'next';

/**
 * Web App Manifest (PWA, J9).
 *
 * Generated by Next.js 16 native `app/manifest.ts` convention. Served at
 * `/manifest.webmanifest` with `Content-Type: application/manifest+json`
 * (handled by Next.js automatically). Static at build — rebuild to change
 * colors or icons.
 *
 * Why J9 needs this:
 * - "Add to Home Screen" on iOS Safari + Android Chrome requires a manifest
 *   (the standalone PWA install path).
 * - `display: 'standalone'` + `start_url: '/dashboard'` makes the launched app
 *   open directly on the dashboard, hiding the URL bar — required for the
 *   Web Push permission prompt to actually be shown on iOS 16.4+.
 * - `theme_color` + `background_color` paint the splash screen and the iOS
 *   status bar in our deep-space dark — DS-v2 token `--bg-1`.
 *
 * Icons:
 * - SVG (`favicon.svg`): vector source, renders crisp at any size, used by
 *   modern browsers + Android.
 * - PNG 1920×1080 (`logo.png`): legacy fallback for Android Chrome that
 *   still wants raster — `sizes: 'any'` lets it use this for splash too.
 * - Tour 15 — dedicated 192×192 + 512×512 raster squares, in BOTH `any`
 *   (rounded backplate) and `maskable` (full-bleed, mark inside the 80% safe
 *   circle) purposes. Generated statically by `scripts/generate-pwa-icons.mjs`
 *   (sharp) so the Android adaptive-icon / "Add to Home Screen" path has real
 *   squares instead of falling back to the SVG. Re-run the script + commit the
 *   PNGs after a brand/colour change.
 *
 * Mark Douglas posture (no-FOMO):
 * - `name` = "Fxmily" (sober, factual — no marketing buzzword)
 * - `description` = neutral one-liner, no "best", no "trader power", no exhort
 *
 * SPEC §2 alignment: this file ships the visible PWA identity for the
 * formation Fxmily. Eliott's preference (memory `feedback_premium_frontend.md`)
 * is enforced by the lime accent + mercury shadows of the launched app, not
 * by the manifest itself — the manifest is the soberest of all the surfaces.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'Fxmily',
    short_name: 'Fxmily',
    description:
      'Suivi comportemental. Formation de trading Fxmily. Discipline, exécution, psychologie.',
    start_url: '/dashboard',
    scope: '/',
    display: 'standalone',
    orientation: 'portrait',
    /// Deep space DS-v2 (`--bg-1`). Painted on the iOS splash + Android task switcher.
    background_color: '#07090f',
    /// Same as background — keeps the iOS status bar dark + matte to match the app.
    theme_color: '#07090f',
    lang: 'fr',
    dir: 'ltr',
    categories: ['finance', 'productivity'],
    icons: [
      {
        src: '/favicon.svg',
        sizes: 'any',
        type: 'image/svg+xml',
        // 'any maskable' lets Android use the same SVG for both contexts.
        // Apple ignores `purpose: 'maskable'` and falls back to apple-touch-icon
        // links in `<head>` (set in `app/layout.tsx`).
        purpose: 'any',
      },
      // J10 Phase K — dedicated raster icons generated by `app/icon.tsx`
      // and `app/apple-icon.tsx` via Next.js 16 ImageResponse convention.
      {
        src: '/apple-icon',
        sizes: '180x180',
        type: 'image/png',
        purpose: 'any',
      },
      {
        src: '/icon',
        sizes: '32x32',
        type: 'image/png',
        purpose: 'any',
      },
      // Tour 15 — PWA install squares (static PNG, scripts/generate-pwa-icons.mjs).
      // `any` = rounded backplate ; `maskable` = full-bleed with the mark inside
      // the 80% safe circle, so Android adaptive masks never clip the logo.
      {
        src: '/icon-192.png',
        sizes: '192x192',
        type: 'image/png',
        purpose: 'any',
      },
      {
        src: '/icon-512.png',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'any',
      },
      {
        src: '/icon-maskable-192.png',
        sizes: '192x192',
        type: 'image/png',
        purpose: 'maskable',
      },
      {
        src: '/icon-maskable-512.png',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'maskable',
      },
      {
        src: '/logo.png',
        sizes: '1920x1080',
        type: 'image/png',
        purpose: 'any',
      },
    ],
  };
}
