/**
 * Next.js 16 renamed `middleware.ts` → `proxy.ts` and changed the export name
 * from `middleware` → `proxy`. We use Auth.js v5's `auth()` helper as a thin
 * wrapper around the edge-compat `authConfig` so route protection runs without
 * pulling Prisma / argon2 into the proxy bundle.
 *
 * The `authorized` callback in `auth.config.ts` makes the actual decisions.
 *
 * P2 quick-win (2026-07-11) — the default export is now a manual wrapper:
 * `/monitoring` (Sentry tunnelRoute) is rate-limited here via
 * `sentryTunnelLimiter` BEFORE the Sentry plugin rewrite forwards the
 * envelope; every other matched path delegates to the Auth.js middleware
 * unchanged. The limiter lives in `token-bucket-core` (marker-free) because
 * the middleware bundle must not evaluate the `server-only` package.
 */

import NextAuth from 'next-auth';
import { NextResponse } from 'next/server';
import type { NextFetchEvent, NextMiddleware, NextRequest } from 'next/server';

import authConfig from '@/auth.config';
import { callerIdTrusted, sentryTunnelLimiter } from '@/lib/rate-limit/token-bucket-core';

const { auth } = NextAuth(authConfig);

// Auth.js v5's `auth` overloads don't line up exactly with `NextMiddleware`
// (its wrapped-middleware signature types the request as `NextAuthRequest`).
// It IS invocable as a middleware — `export default auth;` relied on exactly
// that — so the cast only re-states what the previous default export already
// assumed, without changing runtime behavior.
const authMiddleware = auth as unknown as NextMiddleware;

export default function proxy(req: NextRequest, event: NextFetchEvent) {
  const { pathname } = req.nextUrl;

  // J10 Phase O review B2 follow-up (V2 wiring, 2026-07-11): the Sentry
  // tunnel route is a plugin-generated rewrite (`withSentryConfig({
  // tunnelRoute: '/monitoring' })` in next.config.ts) — there is no route
  // handler to guard, so the proxy is the only interception point. We
  // rate-limit per client IP (last XFF hop — non-spoofable behind Caddy,
  // V1.12 P1 `header_up X-Forwarded-For {remote_host}`) and NEVER redirect:
  // a 307→/login would silently drop browser-side error reports, and a 429
  // is the documented backpressure signal Sentry SDKs honor (Retry-After).
  if (pathname === '/monitoring' || pathname.startsWith('/monitoring/')) {
    const decision = sentryTunnelLimiter.consume(callerIdTrusted(req));
    if (!decision.allowed) {
      return new NextResponse(null, {
        status: 429,
        headers: {
          'Retry-After': String(Math.max(1, Math.ceil(decision.retryAfterMs / 1000))),
        },
      });
    }
    // Allowed → fall through to the Sentry plugin rewrite (rewrites run
    // after the proxy), skipping the auth gate entirely (public tunnel).
    return NextResponse.next();
  }

  return authMiddleware(req, event);
}

export const config = {
  // First matcher: every path EXCEPT:
  //   - `/api/*`              → owned by their route handlers (each one calls
  //                              `auth()` itself). The proxy emits a 307
  //                              redirect to `/login`, which is wrong for
  //                              JSON APIs — clients expect a 401 JSON body.
  //   - `/monitoring/*`       → excluded from the AUTH matcher but matched by
  //                              the second entry below so the wrapper can
  //                              rate-limit it (sentryTunnelLimiter) without
  //                              ever hitting the auth gate. J10 Phase I
  //                              rationale unchanged: a 307→/login on the
  //                              tunnel would silently drop browser-side
  //                              error reports.
  //   - `/_next/static/*`, `/_next/image/*` → Next runtime
  //   - common static files (favicon, logo, *.svg)
  //
  // Defense in depth: every `/api/*` handler MUST verify `await auth()`
  // before doing anything privileged. See `app/api/uploads/*` for the pattern.
  // J10 Phase K — `apple-icon` and `icon` are dynamically-generated PNG
  // routes from `app/apple-icon.tsx` / `app/icon.tsx` (ImageResponse).
  // They are public assets referenced from `<head>`, so they MUST bypass
  // the auth gate (a 307→/login on a `<link rel="apple-touch-icon">`
  // request would just paint a broken icon, not log the user in).
  // J10 Phase R fix — additional public assets that MUST bypass the auth
  // gate :
  //  - `manifest.webmanifest` (Next 16 native, generated by `app/manifest.ts`)
  //    → required by `<link rel="manifest">` for PWA "Add to Home Screen".
  //  - `sw.js` (service worker static asset in `public/sw.js`) → required
  //    for Web Push registration even on anonymous routes.
  //  - `robots.txt` + `sitemap.xml` → SEO crawlers must read them anonymously.
  // Without these excludes, the proxy 307→/login on every public asset
  // request and PWA install / SEO indexing silently break.
  //
  // Second matcher: `/monitoring/:path*` routes the Sentry tunnel through
  // the wrapper above (rate-limit branch only — auth is short-circuited).
  matcher: [
    '/((?!api|monitoring|apple-icon|icon|manifest\\.webmanifest|sw\\.js|robots\\.txt|sitemap\\.xml|_next/static|_next/image|favicon.ico|logo.png|.*\\.svg).*)',
    '/monitoring/:path*',
  ],
};
