/**
 * Next.js 16 renamed `middleware.ts` → `proxy.ts` and changed the export name
 * from `middleware` → `proxy`. We use Auth.js v5's `auth()` helper as a thin
 * wrapper around the edge-compat `authConfig` so route protection runs without
 * pulling Prisma / argon2 into the proxy bundle.
 *
 * The `authorized` callback in `auth.config.ts` makes the actual decisions.
 */

import NextAuth from 'next-auth';

import authConfig from '@/auth.config';

const { auth } = NextAuth(authConfig);

export default auth;

export const config = {
  // Match every path EXCEPT:
  //   - `/api/*`              → owned by their route handlers (each one calls
  //                              `auth()` itself). The proxy emits a 307
  //                              redirect to `/login`, which is wrong for
  //                              JSON APIs — clients expect a 401 JSON body.
  //   - `/monitoring/*`       → Sentry tunnelRoute (J10 Phase I — defense
  //                              against `/monitoring` being treated as
  //                              authenticated and 307-redirected to /login,
  //                              which would silently drop browser-side
  //                              error reports).
  //                              ⚠️ J10 Phase O review B2 correction : the
  //                              tunnel route is auto-generated by the
  //                              Sentry plugin (`withSentryConfig({
  //                              tunnelRoute: '/monitoring' })`) — no
  //                              custom rate-limit code is wired around it
  //                              (the prior comment claiming so was wrong).
  //                              We rely on Sentry's server-side spike
  //                              protection + DSN-level access control
  //                              (DSN is public but rate-limited 90 req/s
  //                              per project on Sentry's edge). For tighter
  //                              defense, V2 can add a custom middleware
  //                              that consumes `sentryTunnelLimiter` before
  //                              forwarding to the Sentry plugin route.
  //   - `/_next/static/*`, `/_next/image/*` → Next runtime
  //   - common static files (favicon, logo, *.svg)
  //
  // Defense in depth: every `/api/*` handler MUST verify `await auth()`
  // before doing anything privileged. See `app/api/uploads/*` for the pattern.
  // J10 Phase K — `apple-icon` and `icon` are dynamically-generated PNG
  // routes from `app/apple-icon.tsx` / `app/icon.tsx` (ImageResponse).
  // They are public assets referenced from `<head>`, so they MUST bypass
  // the auth gate (a 307→/login on a `<link rel="apple-touch-icon">`
  // request would just paint a broken icon, not log the user in).
  matcher: [
    '/((?!api|monitoring|apple-icon|icon|_next/static|_next/image|favicon.ico|logo.png|.*\\.svg).*)',
  ],
};
