/**
 * §32-1 (S6) — DETERMINISTIC calendar-conflict detection.
 *
 * The weekly plan is generated by Claude (`lib/calendar/batch.ts`), which is
 * *asked* to emit calm `warnings[]` when it spots a clash. That delegation is
 * non-deterministic: a factual conflict (a demanding block placed on a slot the
 * member declared unavailable, an over-packed day, a meeting commitment with no
 * meeting block reserved) must be caught by a PURE calculation on closed data,
 * never left to the model's goodwill. This module is that calculation; its
 * output is merged into the same `warnings[]` channel (so the existing
 * `AIGeneratedBanner` on `/calendrier` already discloses it — §50) right before
 * the crisis/AMF scan and the persist (see `persistGeneratedCalendars`).
 *
 * PURITY CONTRACT (enforced by `test/anti-leak/calendar-isolation.test.ts`,
 * which globs `lib/calendar/**`): no DB, no env, no `server-only`, no
 * `Date.now()`. Same input ⇒ same output. The §2 firewall is therefore
 * structural — this file cannot touch a P&L surface even by accident.
 *
 * Posture §2 (BLOQUANT): every message organises TIME (availability, load,
 * meeting time), NEVER a market call — the merged text still passes the AMF
 * scan in `batch.ts`. Anti-Black-Hat §31.2: calm, amber-benevolent, never red,
 * never punitive ("pense à…", never "tu es en retard").
 */

import type {
  CalendarBlockCategoryValue,
  AdaptiveCalendarOutput,
} from '@/lib/schemas/adaptive-calendar';
import type { WeeklyScheduleResponses } from '@/lib/schemas/weekly-schedule-questionnaire';
import type { CalendarSlotValue } from '@/lib/calendar/instrument-v1';

/**
 * Max merged warnings. Mirrors `MAX_WARNINGS` in `adaptive-calendar.ts` — the
 * defensive re-parse in `batch.ts` re-enforces this bound on the persisted row,
 * so this constant is the *intent*, not the only guard.
 */
const MAX_MERGED_WARNINGS = 3;

/** Each message stays within the Zod `WARNING_MAX` (200) bound by construction. */
const WARNING_MAX = 200;

/**
 * Categories that actually *demand* the member's presence/focus. `rest` and
 * `free` never create a conflict (resting on an "unavailable" slot is fine, and
 * a free block carries no obligation), so they are excluded from every rule.
 */
const DEMANDING_CATEGORIES: ReadonlySet<CalendarBlockCategoryValue> = new Set([
  'live_trading',
  'backtest',
  'mark_douglas_review',
  'checkin',
  'meeting',
]);

/** A day is "overloaded" past either bound (whichever trips first). */
const OVERLOAD_BLOCK_COUNT = 6; // ≥6 demanding blocks in a single day
const OVERLOAD_TOTAL_MINUTES = 480; // ≥8h of demanding practice stacked in one day

/** Index 0..6 → French weekday name (output.days is Monday-anchored, length 7). */
const DAY_NAMES_FR = [
  'lundi',
  'mardi',
  'mercredi',
  'jeudi',
  'vendredi',
  'samedi',
  'dimanche',
] as const;

const SLOT_LABEL_FR: Record<CalendarSlotValue, string> = {
  morning: 'le matin',
  afternoon: "l'après-midi",
  evening: 'le soir',
};

const WEEKDAY_KEYS = ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'] as const;
const WEEKEND_KEYS = ['saturday', 'sunday'] as const;

/**
 * Did the member declare themselves available on `(dayIndex, slot)` ? Maps the
 * Monday-anchored day index to the right availability grid. Defensive on an
 * out-of-range index (returns `true` = "no conflict") even though the Zod
 * `.length(7)` schema guarantees 0..6 — `noUncheckedIndexedAccess` strict.
 */
function isSlotAvailable(
  responses: WeeklyScheduleResponses,
  dayIndex: number,
  slot: CalendarSlotValue,
): boolean {
  if (dayIndex >= 0 && dayIndex <= 4) {
    const key = WEEKDAY_KEYS[dayIndex];
    if (!key) return true;
    return responses.weekdayAvailability[key][slot];
  }
  if (dayIndex >= 5 && dayIndex <= 6) {
    const key = WEEKEND_KEYS[dayIndex - 5];
    if (!key) return true;
    return responses.weekendAvailability[key][slot];
  }
  return true;
}

/** Truncate a French day list to at most 3 names ("lundi, mardi, mercredi"). */
function joinDays(indices: readonly number[]): string {
  const names: string[] = [];
  for (const i of indices) {
    const name = DAY_NAMES_FR[i];
    if (name) names.push(name);
  }
  if (names.length <= 3) return names.join(', ');
  return `${names.slice(0, 3).join(', ')}…`;
}

/** Defensive clamp so a built message can never breach the Zod warning bound. */
function clamp(message: string): string {
  return message.length <= WARNING_MAX
    ? message
    : `${message.slice(0, WARNING_MAX - 1).trimEnd()}…`;
}

/**
 * Detect the three brief-named conflicts (§32-1: declared-obligation overlap,
 * predictable meeting absence, overloaded day) between the member's closed
 * answers and the generated plan. Returns 0..N calm messages (uncapped here —
 * `mergeWarnings` applies the cap). PURE.
 */
export function detectCalendarConflicts(
  responses: WeeklyScheduleResponses,
  output: AdaptiveCalendarOutput,
): string[] {
  const messages: string[] = [];

  // Rule 1 — demanding block placed on a slot the member declared unavailable
  // ("créneau qui chevauche une obligation déclarée travail/études"). The
  // strongest, fully-deterministic conflict. Aggregate to ONE calm message so
  // we never spam (anti-Black-Hat); collect the distinct day indices touched.
  const unavailableDays = new Set<number>();
  let firstSlotLabel: string | null = null;
  output.days.forEach((day, dayIndex) => {
    for (const block of day.blocks) {
      if (!DEMANDING_CATEGORIES.has(block.category)) continue;
      if (!isSlotAvailable(responses, dayIndex, block.slot)) {
        unavailableDays.add(dayIndex);
        firstSlotLabel ??= SLOT_LABEL_FR[block.slot];
      }
    }
  });
  if (unavailableDays.size > 0) {
    const indices = [...unavailableDays].sort((a, b) => a - b);
    if (indices.length === 1 && firstSlotLabel) {
      messages.push(
        clamp(
          `Un créneau de pratique est prévu ${DAY_NAMES_FR[indices[0]!]} ${firstSlotLabel}, un moment où tu t'es dit indisponible. Pense à le décaler ou à ajuster ta disponibilité.`,
        ),
      );
    } else {
      messages.push(
        clamp(
          `Des créneaux de pratique tombent sur des moments où tu t'es dit indisponible (${joinDays(indices)}). Pense à les décaler ou à ajuster ta disponibilité.`,
        ),
      );
    }
  }

  // Rule 2 — overloaded day ("journée surchargée"). Either too many demanding
  // blocks OR too many stacked minutes in a single day. Aggregate the day list.
  const overloadedDays: number[] = [];
  output.days.forEach((day, dayIndex) => {
    let count = 0;
    let minutes = 0;
    for (const block of day.blocks) {
      if (!DEMANDING_CATEGORIES.has(block.category)) continue;
      count += 1;
      minutes += block.durationMin;
    }
    if (count >= OVERLOAD_BLOCK_COUNT || minutes >= OVERLOAD_TOTAL_MINUTES) {
      overloadedDays.push(dayIndex);
    }
  });
  if (overloadedDays.length > 0) {
    messages.push(
      clamp(
        `Journée chargée (${joinDays(overloadedDays)}) — beaucoup de pratique prévue d'affilée. Garde un peu de marge pour souffler et rester régulier.`,
      ),
    );
  }

  // Rule 3 — meeting commitment with no meeting block reserved ("absence
  // prévisible à une réunion"). Only the firm "regular" commitment fires, to
  // stay calm: an "occasional" week legitimately needs no reserved slot.
  if (responses.meetingCommitment === 'regular') {
    const hasMeetingBlock = output.days.some((day) =>
      day.blocks.some((block) => block.category === 'meeting'),
    );
    if (!hasMeetingBlock) {
      messages.push(
        clamp(
          "Tu visais des réunions régulières cette semaine, mais aucune n'est encore bloquée dans ton plan. Pense à réserver un créneau pour y assister.",
        ),
      );
    }
  }

  return messages;
}

/**
 * Merge the model's own `warnings[]` with the deterministic conflicts.
 *
 * Order: **conflicts first** (server-truth, factual, always correct), then the
 * model's calmer context notes — so a verbose model can never push a hard
 * factual conflict out of the 3-slot cap. Exact dedupe (trim + lowercase +
 * whitespace-collapsed) drops a model note that already says the same thing.
 * Capped at {@link MAX_MERGED_WARNINGS}; the `batch.ts` re-parse re-enforces it.
 */
export function mergeWarnings(
  modelWarnings: readonly string[],
  conflicts: readonly string[],
): string[] {
  const out: string[] = [];
  const seen = new Set<string>();
  const norm = (s: string) => s.trim().toLowerCase().replace(/\s+/g, ' ');

  for (const message of [...conflicts, ...modelWarnings]) {
    const trimmed = message.trim();
    if (!trimmed) continue;
    const key = norm(trimmed);
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(trimmed);
    if (out.length >= MAX_MERGED_WARNINGS) break;
  }

  return out;
}
