#!/usr/bin/env bash
# Healthchecks.io setup — externalize Fxmily Cron Watch from GitHub Actions
# (free tier 20 checks). Saves ~730 min/month GHA quota + eliminates the
# recurring CRON_SECRET sync mismatch bug seen during V1.6 hardening.
#
# Usage :
#   1. Sign up free at https://healthchecks.io (no CB required, 20 checks)
#   2. Generate API token : Account → API Access → Read-Write key
#   3. HEALTHCHECKS_API_TOKEN=hcat_xxx bash ops/scripts/healthchecks-setup.sh provision
#   4. Then `bash ops/scripts/healthchecks-setup.sh hetzner-crontab` to print
#      the new Hetzner crontab lines that ping Healthchecks after each cron run
#   5. Update /etc/cron.d/fxmily-app on Hetzner (via SSH) with the new lines
#   6. Disable .github/workflows/cron-watch.yml (rename to .disabled or delete)
#
# Cost : $0 (Healthchecks free tier covers Fxmily V1+V2 even at 1000 members).

set -euo pipefail

HEALTHCHECKS_API_BASE="${HEALTHCHECKS_API_BASE:-https://healthchecks.io/api/v3}"
HEALTHCHECKS_PING_BASE="https://hc-ping.com"

# 9 Fxmily cron jobs (V1.6 state) — slug | cron schedule | grace timeout
#
# `cron.health` is the meta-watcher emitted by `/api/cron/health` (J10 Phase J)
# and serves as the canary for the whole cron pipeline.
CRONS=(
  "checkin-reminders|*/15 7-22 * * *|600"
  "recompute-scores|0 2 * * *|3600"
  "dispatch-douglas|0 */6 * * *|3600"
  "dispatch-notifications|*/2 * * * *|300"
  "weekly-reports|0 21 * * 0|7200"
  "purge-deleted|0 3 * * *|3600"
  "purge-push-subscriptions|0 4 * * 0|3600"
  "purge-audit-log|0 4 * * *|3600"
  "health|0 * * * *|7200"
)

cmd_provision() {
  : "${HEALTHCHECKS_API_TOKEN:?Set HEALTHCHECKS_API_TOKEN (Account → API Access)}"

  if ! command -v curl >/dev/null 2>&1; then
    echo "ERROR: curl is required" >&2
    exit 1
  fi

  echo "Provisioning 9 Healthchecks.io checks for Fxmily prod..."
  echo

  for entry in "${CRONS[@]}"; do
    IFS='|' read -r slug schedule grace <<<"$entry"

    response=$(curl -fsS -X POST "${HEALTHCHECKS_API_BASE}/checks/" \
      -H "X-Api-Key: ${HEALTHCHECKS_API_TOKEN}" \
      -H "Content-Type: application/json" \
      --data-raw "$(cat <<JSON
{
  "name": "fxmily.cron.${slug}",
  "slug": "fxmily-cron-${slug}",
  "tz": "Europe/Paris",
  "schedule": "${schedule}",
  "grace": ${grace},
  "tags": "fxmily prod cron",
  "unique": ["slug"]
}
JSON
)")

    ping_url=$(echo "$response" | sed -n 's/.*"ping_url"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p')
    if [ -z "$ping_url" ]; then
      echo "  WARNING: could not parse ping_url for cron.${slug} (response: $response)"
    else
      uuid=${ping_url##*/}
      echo "  ✓ cron.${slug} → ${ping_url}"
      echo "    UUID=${uuid}" >>".healthchecks-ping-urls.tmp"
    fi
  done

  echo
  echo "Provisioning complete. Next : run 'hetzner-crontab' subcommand."
  echo "Ping URLs saved to .healthchecks-ping-urls.tmp (gitignored)."
}

cmd_hetzner_crontab() {
  cat <<'EOF'
# Updated /etc/cron.d/fxmily-app for Hetzner — pings Healthchecks.io after
# each successful cron run. Replace YOUR_UUID_xxx with the UUIDs from
# .healthchecks-ping-urls.tmp (generated by `provision` subcommand).
#
# Pattern : `fxmily-cron <slug> && curl -fsS -m 10 --retry 3 https://hc-ping.com/UUID`
# The `&&` makes the ping conditional on cron job success ; Healthchecks
# auto-fires the alert if the ping doesn't arrive within `grace` seconds of
# the next scheduled run.
#
# Failure mode : if the cron command itself fails (`!&&`), no ping → grace
# timeout → Healthchecks alert. Perfect for "cron is broken" detection.

# crontab format : minute hour day month dow user command
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# Cron 1: check-in reminders (every 15 min during 7-22 local Paris)
*/15 7-22 * * * fxmily /usr/local/bin/fxmily-cron checkin-reminders && curl -fsS -m 10 --retry 3 https://hc-ping.com/YOUR_UUID_CHECKIN_REMINDERS

# Cron 2: nightly behavioral score recompute
0 2 * * * fxmily /usr/local/bin/fxmily-cron recompute-scores && curl -fsS -m 10 --retry 3 https://hc-ping.com/YOUR_UUID_RECOMPUTE_SCORES

# Cron 3: Mark Douglas dispatch every 6h
0 */6 * * * fxmily /usr/local/bin/fxmily-cron dispatch-douglas && curl -fsS -m 10 --retry 3 https://hc-ping.com/YOUR_UUID_DISPATCH_DOUGLAS

# Cron 4: push notifications dispatch every 2 min
*/2 * * * * fxmily /usr/local/bin/fxmily-cron dispatch-notifications && curl -fsS -m 10 --retry 3 https://hc-ping.com/YOUR_UUID_DISPATCH_NOTIFICATIONS

# Cron 5: weekly AI digest (Sunday 21:00 UTC)
0 21 * * 0 fxmily /usr/local/bin/fxmily-cron weekly-reports && curl -fsS -m 10 --retry 3 https://hc-ping.com/YOUR_UUID_WEEKLY_REPORTS

# Cron 6: purge soft-deleted users
0 3 * * * fxmily /usr/local/bin/fxmily-cron purge-deleted && curl -fsS -m 10 --retry 3 https://hc-ping.com/YOUR_UUID_PURGE_DELETED

# Cron 7: purge stale push subscriptions (weekly, Sunday 4am)
0 4 * * 0 fxmily /usr/local/bin/fxmily-cron purge-push-subscriptions && curl -fsS -m 10 --retry 3 https://hc-ping.com/YOUR_UUID_PURGE_PUSH_SUBSCRIPTIONS

# Cron 8: purge audit log >90j
0 4 * * * fxmily /usr/local/bin/fxmily-cron purge-audit-log && curl -fsS -m 10 --retry 3 https://hc-ping.com/YOUR_UUID_PURGE_AUDIT_LOG

# Cron 9: health canary (hourly)
0 * * * * fxmily /usr/local/bin/fxmily-cron health && curl -fsS -m 10 --retry 3 https://hc-ping.com/YOUR_UUID_HEALTH

# Daily backup (existing, no Healthchecks ping yet — V2 candidate)
30 2 * * * fxmily /usr/local/bin/fxmily-backup
EOF
}

cmd_disable_gha_cronwatch() {
  cat <<'EOF'
# Disable the GHA Cron Watch workflow once Healthchecks.io is healthy.
# Run from the worktree root :

mv .github/workflows/cron-watch.yml .github/workflows/cron-watch.yml.disabled

# Or delete entirely if you trust Healthchecks :
# rm .github/workflows/cron-watch.yml

# Then commit + push. Saves ~730 min/month GHA quota.
EOF
}

cmd_verify() {
  : "${HEALTHCHECKS_API_TOKEN:?Set HEALTHCHECKS_API_TOKEN}"
  echo "Listing Fxmily checks on Healthchecks.io..."
  curl -fsS "${HEALTHCHECKS_API_BASE}/checks/" \
    -H "X-Api-Key: ${HEALTHCHECKS_API_TOKEN}" |
    sed -n 's/.*"name"[[:space:]]*:[[:space:]]*"\(fxmily[^"]*\)".*"status"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/  \1 → \2/p'
}

usage() {
  cat <<'EOF'
Usage : bash ops/scripts/healthchecks-setup.sh <subcommand>

Subcommands :
  provision           — Create the 9 Fxmily cron checks on Healthchecks.io
  hetzner-crontab     — Print the updated Hetzner crontab lines (copy-paste)
  disable-gha-cronwatch — Print instructions to disable the GHA Cron Watch workflow
  verify              — List provisioned checks + their last-ping status

Environment :
  HEALTHCHECKS_API_TOKEN — Read-Write API key from Healthchecks.io Account

Cost : $0 (free tier 20 checks). Fxmily uses 9 slots.
EOF
}

case "${1:-}" in
  provision) cmd_provision ;;
  hetzner-crontab) cmd_hetzner_crontab ;;
  disable-gha-cronwatch) cmd_disable_gha_cronwatch ;;
  verify) cmd_verify ;;
  *) usage; exit 1 ;;
esac
